version: '3'
services:
  db:
    image: postgres:14.3-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parser
    ports:
      - "5433:5432"

